cache:
  enable: true

scheme: Gemini

minify: true


favicon:
  small: favicon-16x16.png
  medium: favicon-32x32.png
  apple_touch_icon: logo.png
  safari_pinned_tab: logo.png


creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-nc-sa
  # Available values: big | small
  size: small
  sidebar: true
  post: true
  language: deed.zh

sidebar:
  # Sidebar position. Available values: left | right
  position: left

  # Sidebar width.
  # Applicable to Muse | Mist and mobile of Pisces | Gemini.
  width_expanded: 320
  # Applicable to desktop of Pisces | Gemini.
  width_dual_column: 240

  # Sidebar display.
  # Applicable to Muse | Mist and mobile of Pisces | Gemini.
  # Available values:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically.
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  totally remove sidebar including sidebar toggle.
  display: post

  # Sidebar padding in pixels.
  padding: 18
  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12

save_scroll: true

language_switcher: true

language:
- zh-CN
- en

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  免费ChatGPT: https://freegpt.tech/?refer=blog-side || fa fa-heart
  我的简历: https://leadscloud.github.io/resume/resume.pdf || fa fa-vcard
  友情链接: /links/ || fa fa-link
  Chrome扩展（域名所属人）: /serp-analyzer/ || fa fa-cloud
  询盘管理系统: https://github.com/leadscloud/infomaster || fa fa-database
  外贸留言板系统: /20180615/google-seo-inquiry-messageboard/ || fa fa-database
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
  # Linuxdo论坛(新的理想型社区): https://linux.do/?source=leadscloud_github_io || fa fa-link

menu_settings:
  icons: true
  badges: true

social:
  GitHub: https://github.com/leadscloud || fab fa-github
  E-Mail: mailto:love4026@gmail.com || fa fa-envelope

links:
  RLiveChat: https://cdn.livechatinc.xyz/
  Roadheader: https://www.kamychina.com/
  TinyCMS: https://tinycms.xyz/

# Google Analytics
# See: https://analytics.google.com
google_analytics:
  tracking_id: G-6GCT2E7T9Y
  # By default, NexT will load an external gtag.js script on your site.
  # If you only need the pageview feature, set the following option to true to get a better performance.
  only_pageview: false
  # only needed if you are using `only_pageview` mode, https://developers.google.com/analytics/devguides/collection/protocol/ga4
  measure_protocol_api_secret:

# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: far fa-eye

# Algolia Search
# For more information: https://www.algolia.com
algolia_search:
  enable: true
  hits:
    per_page: 10

leancloud_visitors:
  enable: true
  app_id: ePPAQV9hFzcbhOaQvvtyjTnw-gzGzoHsz #<app_id>
  app_key: GLniGVXsSMGBjTmaiI4wleaF #<app_key>
  server_url: https://leancloud.tinycms.xyz
  security: false


# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  enable: true
  appId:  ePPAQV9hFzcbhOaQvvtyjTnw-gzGzoHsz
  appKey:  GLniGVXsSMGBjTmaiI4wleaF
  serverURLs: https://leancloud.tinycms.xyz
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  meta: [nick, mail, link] # Custom comment header
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: true # Whether to record the commenter IP
  enableQQ: true
  lang: zh-cn

github_banner:
  enable: true
  permalink: https://github.com/leadscloud